### ISSUE TITLE
Doesn't work with Python 3 on Mac OS

### ISSUE THREAD

**Issue by akodkod** [mtojo/node-system-icon#1]
Hellp,

I've tried to install package with Python 3 and got error:

```
error /Users/***/Projects/SIMS/Code/sims-offline-sync/node_modules/system-icon: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/***/Projects/SIMS/Code/sims-offline-sync/node_modules/system-icon
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.6.1 | darwin | x64
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/local/bin/python" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/***/.config/yarn/global/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/***/.config/yarn/global/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:264:7)
gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:933:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:353:11)
gyp ERR! stack     at Socket.emit (events.js:127:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:550:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/Cellar/node/9.6.1/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/***/Projects/SIMS/Code/sims-offline-sync/node_modules/system-icon

```

**Comment by mtojo** [comment]
Python 3 is not supported for node-gyp.

https://github.com/nodejs/node-gyp#on-mac-os-x

> python (v2.7 recommended, v3.x.x is not supported) (already installed on Mac OS X)

**Comment by akodkod** [comment]
@mtojo thank you. My fault, already reinstalled with Python 2.7 and everything works!

P.S. Issue can be closed

**Comment by mtojo** [comment]
👍
